import 'package:Zowwad/constants/constants.dart';
import 'package:Zowwad/dto/FacultyBook/book_dto.dart';

final List<BookDto> items = [
  BookDto(
    id: 1,
    userName: "مستخدم تجريبي",
    facultyName: "علوم الحاسوب",
    title: "مقدمة في الخوارزميات",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "جديد",
    status: "متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 2,
    userName: "مستخدم تجريبي",
    facultyName: "علوم الحاسوب",
    title: "شبكات الحاسوب: النهج العلوي",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "جديد",
    status: "متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 3,
    userName: "مستخدم تجريبي",
    facultyName: "علوم الحاسوب",
    title: "مفاهيم نظم التشغيل",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "مستعمل",
    status: "غير متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 4,
    userName: "مستخدم تجريبي",
    facultyName: "الهندسة",
    title: "الميكانيكا الهندسية: السكون والحركة",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "مستعمل",
    status: "غير متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 5,
    userName: "مستخدم تجريبي",
    facultyName: "رياضيات",
    title: "حساب التفاضل والتكامل: المتغيرات المبكرة",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "جديد",
    status: "متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 6,
    userName: "مستخدم تجريبي",
    facultyName: "رياضيات",
    title: "الجبر الخطي وتطبيقاته",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "جديد",
    status: "متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 7,
    userName: "مستخدم تجريبي",
    facultyName: "إحصاء",
    title: "الاحتمالات والإحصاء",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "جديد",
    status: "متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 8,
    userName: "مستخدم تجريبي",
    facultyName: "علوم",
    title: "الفيزياء للعلماء والمهندسين",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "مستعمل",
    status: "غير متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 9,
    userName: "مستخدم تجريبي",
    facultyName: "كيمياء",
    title: "الكيمياء: العلم المركزي",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "جديد",
    status: "متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 10,
    userName: "مستخدم تجريبي",
    facultyName: "أحياء",
    title: "علم الأحياء كامبل",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "جديد",
    status: "متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 11,
    userName: "مستخدم تجريبي",
    facultyName: "اقتصاد",
    title: "مبادئ الاقتصاد",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "مستعمل",
    status: "غير متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 12,
    userName: "مستخدم تجريبي",
    facultyName: "مالية",
    title: "المالية المؤسسية",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "جديد",
    status: "متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 13,
    userName: "مستخدم تجريبي",
    facultyName: "تسويق",
    title: "إدارة التسويق",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "مستعمل",
    status: "غير متوفر",
    createdAt: "2024-01-01",
  ),
  BookDto(
    id: 14,
    userName: "مستخدم تجريبي",
    facultyName: "اجتماع",
    title: "علم الاجتماع",
    author: null,
    image: uniBook,
    coverImage: null,
    condition: "جديد",
    status: "متوفر",
    createdAt: "2024-01-01",
  ),
];